/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

// MUSIC
export const LOAD_MUSIC = 'LOAD_MUSIC'
export const LOADING_MUSIC = 'LOADING_MUSIC'
export const TOGGLE_PLAY = 'TOGGLE_PLAY'

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const CURRENT_USER = 'CURRENT_USER';
export const STORE_USER = 'STORE_USER';
export const CHECK_AUTH = 'CHECK_AUTH';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';
